### ISSUE TITLE
in the demo app- how to sign in ? as its continuously giving errors and what are the addresses we are looking for?  also how to run it on Ganache personal blockchain locally?

### ISSUE THREAD

**Issue by rpriyanshu** [jayateertha043/Decentralized-Medical-Records#1]

**Comment by jayateertha043** [comment]
The demo app url and the project is configued to be run along with metamask extension in rinkeby network.
(This app doesn't support ganache by default,metamask and rinkeby is easier and you can access using internet)
Please make sure you have your metamask installed and is on rinkeby network also you have some test eth in your wallet.
The address is etherum wallet address.(Not sure which address you are asking as there is patient address,hospital address,admin address, owner address).

For testing sign up as patient,Upload a record and you can give permission for other hospitals to view your record by granting permission.

**Comment by jayateertha043** [comment]
For Hospital and admin access ,you need to deploy the smart contract on rinkeby network on your own,The person deploying contract will default be owner and also admin,Admin can add more hospitals

**Comment by jayateertha043** [comment]
May be I will try to generate a test ethereum wallet of admin and provide the private key here ,So you can add hospital and test everything

**Comment by jayateertha043** [comment]
I have added a sample admin account private key in readme now,you can add that account into your metamask wallet and try using admin login also add new hospitals.
